# Generated by Django 4.1.12 on 2023-11-05 23:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personaladministrativo', '0001_initial'),
        ('medicos', '0006_ordenayudadiagnostica_costo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.PositiveIntegerField(help_text='Tiempo en días')),
                ('cantidad_visitas_dia', models.PositiveIntegerField(default=1)),
                ('visitas', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=False)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizacion', to='medicos.orden')),
            ],
        ),
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=False)),
                ('orden_hospitalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_de_hospitalizacion', to='enfermeras.hospitalizacion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_hospitalizado', to='personaladministrativo.paciente')),
            ],
        ),
    ]
