# Generated by Django 4.1.12 on 2023-11-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitas',
            name='informacion_adicional',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
