# Generated by Django 4.1.12 on 2023-11-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0006_ordenayudadiagnostica_costo'),
        ('enfermeras', '0004_visitas_nivel_oxigeno_visitas_presion_arterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitas',
            name='medicamentos',
            field=models.ManyToManyField(blank=True, to='medicos.orden'),
        ),
    ]
