# Generated by Django 4.1.12 on 2023-11-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0006_ordenayudadiagnostica_costo'),
        ('enfermeras', '0005_visitas_medicamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='medicamentos',
            field=models.ManyToManyField(blank=True, to='medicos.ordenmedicamento'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='nivel_oxigeno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='pulso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='temperatura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
