# Generated by Django 4.1.12 on 2023-11-04 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personaladministrativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_orden', models.CharField(choices=[('medicamento', 'Medicamento'), ('procedimiento', 'Procedimiento'), ('hospitalizacion', 'Hospitalización'), ('ayuda_diagnostica', 'Ayuda Diagnóstica')], max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaladministrativo.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField()),
                ('nombre_procedimiento', models.CharField(max_length=200)),
                ('numero_veces', models.PositiveIntegerField()),
                ('frecuencia', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requiere_asistencia_especialista', models.BooleanField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='medicos.orden')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField()),
                ('nombre_medicamento', models.CharField(max_length=200)),
                ('dosis', models.CharField(max_length=50)),
                ('duracion_tratamiento', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='medicos.orden')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenAyudaDiagnostica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ayuda_diagnostica', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('requiere_asistencia_especialista', models.BooleanField()),
                ('finalizado', models.BooleanField(default=False)),
                ('resultados', models.CharField(blank=True, max_length=2000)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.orden', verbose_name='Ayuda diagnostica')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo_consulta', models.TextField()),
                ('sintomatologia', models.TextField()),
                ('diagnostico', models.TextField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ordenes', models.ManyToManyField(related_name='historias_clinicas', to='medicos.orden')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaladministrativo.paciente')),
            ],
        ),
    ]
