# Generated by Django 4.1.12 on 2023-11-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='cerrada',
            field=models.BooleanField(default=False),
        ),
    ]
