# Generated by Django 4.1.12 on 2023-11-05 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_alter_historiaclinica_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenayudadiagnostica',
            old_name='finalizado',
            new_name='cerrada',
        ),
        migrations.AddField(
            model_name='orden',
            name='cerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenmedicamento',
            name='cerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenprocedimiento',
            name='cerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_solicitud',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orden',
            name='nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
