# Generated by Django 4.1.12 on 2023-11-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0004_rename_finalizado_ordenayudadiagnostica_cerrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
