# Generated by Django 4.1.12 on 2023-11-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0005_historiaclinica_pagada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenayudadiagnostica',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=10),
        ),
    ]
