# Generated by Django 4.1.12 on 2023-10-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usuario_groups_usuario_is_superuser_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nacimiento',
            field=models.DateField(default='2000-01-01', null=True),
        ),
    ]
