# Generated by Django 4.1.12 on 2023-10-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usuario_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(default='111111111', max_length=10, unique=True, verbose_name='Cedula de Ciudadania'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numero de Telefono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=30, verbose_name='Direccion'),
        ),
    ]
