# Generated by Django 4.1.12 on 2023-11-06 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_usuario_apellidos_remove_usuario_nombres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.role', verbose_name='Rol Laboral'),
        ),
    ]
