# Generated by Django 4.1.12 on 2023-10-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=10, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=200)),
                ('numero_telefono', models.CharField(max_length=10)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombre_contacto_emergencia', models.CharField(max_length=200)),
                ('relacion_contacto_emergencia', models.CharField(max_length=50)),
                ('numero_telefono_emergencia', models.CharField(max_length=10)),
                ('nombre_compania_seguro', models.CharField(max_length=100)),
                ('numero_poliza_seguro', models.CharField(max_length=50)),
                ('estado_poliza_seguro', models.BooleanField()),
                ('copagos_acumulados', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
